language: node_js
cache:
  - yarn
  - bundler
before_install:
  - gem update --system
  - gem install bundler
install:
  - yarn install
  - bundle install
script:
  - yarn build:production
  - yarn test
